# Recoverable Errors with Result

Most errors aren’t serious enough to require the program to stop entirely. Sometimes, when a function fails, it’s for a reason that you can easily interpret and respond to. For example, if you try to open a file and that operation fails because the file doesn’t exist, you might want to create the file instead of terminating the process.

Rust’s `Result` enum is used to handle recoverable errors and is defined as:

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

T represents the type of the value returned in a success case, and E represents the type of the error in a failure case. This allows `Result` to be used in many situations where the types of success and error values differ.

### Example: Handling Result

To handle the `Result` value returned by a function, use a `match` expression. For example, when opening a file:

```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {error:?}"),
    };
}
```

If `File::open` succeeds, `Ok` returns a file handle. If it fails, `Err` returns an error, and the code panics.

### Matching on Different Errors

You might want to handle different errors differently. For example, if a file doesn’t exist, create it. If it fails for another reason, panic:

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {e:?}"),
            },
            other_error => {
                panic!("Problem opening the file: {other_error:?}");
            }
        },
    };
}
```

### Using unwrap_or_else

Instead of using multiple `match` expressions, you can use `unwrap_or_else` with closures for a cleaner look:

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {error:?}");
            })
        } else {
            panic!("Problem opening the file: {error:?}");
        }
    });
}
```

### Using unwrap and expect

`unwrap` and `expect` are shortcuts for handling `Result`. `unwrap` returns the value inside `Ok` or panics if it's an `Err`:

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap();
}
```

`expect` is like `unwrap`, but lets you specify a custom panic message:

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")
        .expect("hello.txt should be included in this project");
}
```

### Propagating Errors

Instead of handling errors within a function, you can return them to the calling code:

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e),
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
```

### Using the ? Operator

The `?` operator is a shorthand for propagating errors:

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```

You can chain method calls with `?`:

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();
    File::open("hello.txt")?.read_to_string(&mut username)?;
    Ok(username)
}
```

Or use `fs::read_to_string` for common operations:

```rust
use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```

### Where The ? Operator Can Be Used

The `?` operator can only be used in functions that return `Result`, `Option`, or another type that implements `FromResidual`.

```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")?;
}
```

This code will not compile because `main` returns `()` instead of `Result`.

To fix it, change the return type of `main`:

```rust
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
    let greeting_file = File::open("hello.txt")?;
    Ok(())
}
```

Now that we’ve discussed `panic!` and `Result`, we can decide when to use each approach.